### ISSUE TITLE
Any support for HID coming?

### ISSUE THREAD

**Issue by tux7k** [jannic/rp-microcontroller-rs#10]
I'm trying to find out how HID works so I could send keystrokes but how would you do that?

**Comment by jannic** [comment]
AFAIK there is no support yet to do this in Rust on an rp2040.
For an example how it could look like, https://github.com/jannic/pikvm-hid-stm32 is a prototype implementation for a device using USB HID to send keystrokes in Rust, but for an stm32f103 microcontroller. Once there is a sufficiently complete rust HAL for the rp2040, a port would probably look very similar.
There are HID examples for the rp2040 C SDK at https://github.com/raspberrypi/pico-examples/tree/master/usb/device. If you want to do something on the rp2040 now, it's probably your best bet, but obviously it's not Rust but C.
