### ISSUE TITLE
UART over usb

### ISSUE THREAD

**Issue by OliverBrotchie** [jannic/rp-microcontroller-rs#9]
Could you please provide an example of how one would communicate over the USB connection using UART?
Apologies if this is not doable! I am completely new to programming microcontrollers.

**Comment by jannic** [comment]
Hi @OliverBrotchie,
as far as I know there is no Rust driver for the USB peripheral of the rp-2040, yet. So it's not yet possible to configure the rp-2040 USB port as a UART device. (If that's what you are trying to do, I'm not 100% sure if I understood your question correctly.)

**Comment by tuckotb** [comment]
I'm pretty sure he means serial communication

**Comment by jannic** [comment]
Closing this ticket, as I don't think there is anything to do at the moment.
